### ISSUE TITLE
Routing & eine Zukunft nach OLSRv1

### ISSUE THREAD

**Issue by pktpls** [freifunk-berlin/meta#3]
Am ~~9.9.~~ 16.9. wollen wir uns einen Tag zusammensetzen und diverse größere Themen behandeln. Eins davon ist Routing und eine Zukunft nach OLSRv1.

Hier würde ich gerne alle Infos zum Status Quo, zukünftigen Optionen und möglichen nächsten Schritten sammeln, damit wir am  ~~9.9.~~ 16.9. alle auf dem gleichen Stand sind. Bitte ergänzt sehr gerne weitere Infos oder auch weitere Aspekte die zu diskutieren wären.

*(Ich hab mehr Notizen zu verschriftlichen, wollte nur schon mal das Issue eröffnen damit es verlinkt werden kann.)*

**Comment by pmelange** [comment]
The current situation on the entire berlin network for IPv4 is that we are using OLSRv1.  

The killer feature (in my opinion) is the nameservice plugin.  If there is a good alternative to be able to propagate hostnames across the mesh, that would be critical.

Another important feature of using OLSRv1 is that we block gateway announcement at the bbbvpn.  This prevents all those home routers from having to use their DSL lines to route packets to the internet from the backbone.  If we were to migrate to a new routing protocol, I would personally find it important to be able to do something similar.

One issue with changing from OLSRv1 to another routing protocol is that we would need to be able to contact all nodes in the mesh (including those via bbbvpn) and have them upgrade at the same time.  Otherwise, we will be dropping a lot of clients from the network.

**Comment by PolynomialDivision** [comment]
> Another important feature of using OLSRv1 is that we block gateway announcement at the bbbvpn. This prevents all those home routers from having to use their DSL lines to route packets to the internet from the backbone. If we were to migrate to a new routing protocol, I would personally find it important to be able to do something similar.

babel has a very powerful way of filtering and redistributing announcements. That should be easy doable with babeld.

**Comment by pmelange** [comment]
The current situation on the entire berlin network for IPv4 is that we are using OLSRv1.  

The killer feature (in my opinion) is the nameservice plugin.  If there is a good alternative to be able to propagate hostnames across the mesh, that would be critical.

Another important feature of using OLSRv1 is that we block gateway announcement at the bbbvpn.  This prevents all those home routers from having to use their DSL lines to route packets to the internet from the backbone.  If we were to migrate to a new routing protocol, I would personally find it important to be able to do something similar.

One issue with changing from OLSRv1 to another routing protocol is that we would need to be able to contact all nodes in the mesh (including those via bbbvpn) and have them upgrade at the same time.  Otherwise, we will be dropping a lot of clients from the network.

> > Another important feature of using OLSRv1 is that we block gateway announcement at the bbbvpn. This prevents all those home routers from having to use their DSL lines to route packets to the internet from the backbone. If we were to migrate to a new routing protocol, I would personally find it important to be able to do something similar.
> 
> babeld has a very powerful way of filtering and redistributing announcements. That should be easy doable with babeld.

Shall we set up a test?  We can still use bbbdigger to build the l2tp tunnel and push babel over it.

**Comment by pktpls** [comment]
I have a few more notes, but wanted to post this survey first. I'm in favor of Babel too (for mostly pragmatic reasons) but wanted to see what the protocol landscape is like at the moment.

- OLSRv1 https://github.com/OLSR/olsrd
  - viel praktische Erfahrung in Berlin, funktioniert immernoch einigermaßen gut, macht IPv4 in Berlin
  - nicht ganz ideal: langes Bootstrapping, Tendenz zu Loops und Flapping, keine Routemetriken per Interface
  - eine Implementierung, keine nennenswerte Entwicklung seit ca. 2017
- OLSRv2/OONF https://github.com/OLSR/OONF
  - keine praktische Erfahrung damit
  - eine Implementierung, keine nennenswerte Entwicklung seit 2018
- B.A.T.M.A.N. https://git.open-mesh.org/batmand.git
  - keine Entwicklung seit 2014
- batman-adv https://git.open-mesh.org/batmand.git
  - wird immernoch aktiv entwickelt, letztes Release Mai 2023
  - ein bisschen praktische Erfahrung, es gab mal Inselexperimente im BBB (Basti Rosner)
  - Gluon verwendet batman-adv, zumindest gibts ein gluon-mesh-batman-adv package
- BMX7 https://github.com/bmx-routing/bmx7
  - Fork von Batman
  - es geht vor allem um Trust & Security ohne zentrale Stellen, siehe auch die Dissertation von Axel: https://people.ac.upc.edu/leandro/docs/phd_axel.pdf
  - eine Implementierung, keine Entwicklung seit 2018
  - keine praktische Erfahrung damit
- Babel
  - gutes IPv6-Experiment mit BBB-Configs seit 3 Jahren
  - drei aktiv entwickelte Implementierungen
    - babeld https://github.com/jech/babeld
    - bird https://github.com/CZ-NIC/bird
    - go-babel https://github.com/stv0g/go-babel
